name: default

trigger:
  event: commit

pipeline:
  - id: ut
    type: agent
    agent: ut-agent
    base-branch: ${input.node.branch}

  - id: cr
    type: agent
    agent: cr-agent
    depends_on: [ut]
    base-branch: ${steps.ut.node.branch}
